### ISSUE TITLE
测试在mac上无效

### ISSUE THREAD

**Issue by tangdu** [starxg/MyBatisCodeHelperProCrack#1]
配置正确还出现这个
<img width="799" alt="image" src="https://github.com/starxg/MyBatisCodeHelperProCrack/assets/1294394/bd7f0f8d-7b03-46cf-a1ec-6ccdefd487ff">

配置是正确的
`
--add-opens=java.base/jdk.internal.org.objectweb.asm=ALL-UNNAMED
--add-opens=java.base/jdk.internal.org.objectweb.asm.tree=ALL-UNNAMED

-javaagent:/xxxxx/ja-netfilter.jar=jetbrains
`

idea的版本

IntelliJ IDEA 2023.1 (Ultimate Edition)

**Comment by starxg** [comment]
点击激活 提示什么

**Comment by coullin** [comment]
一样， 提示key错误， 你的reademe.md没写清楚下载release里面的哪几个文件，那几个文件怎么放，描述清楚一点呀，那个crack文件也放jar包， 反正试了几次都不行

**Comment by starxg** [comment]
> 一样， 提示key错误， 你的reademe.md没写清楚下载release里面的哪几个文件，那几个文件怎么放，描述清楚一点呀，那个crack文件也放jar包， 反正试了几次都不行

目前只有一个 1.0.0 版本 对应mybatispro这个插件的 3.2.1 版本。

如果没有生效很有可能是版本对应不上导致的，因为 1.0.0 只对 3.2.1 有效

**Comment by starxg** [comment]
我的配置如下

```properties
--add-opens=java.base/jdk.internal.org.objectweb.asm=ALL-UNNAMED
--add-opens=java.base/jdk.internal.org.objectweb.asm.tree=ALL-UNNAMED
-javaagent:/Users/xxx/Software/ja-netfilter-all-main/ja-netfilter.jar=jetbrains
```

<img  alt="image" src="https://github.com/starxg/MyBatisCodeHelperProCrack/assets/34997494/e01c1ff0-2b36-4f7d-ab61-e21d6be2c6f5">

**Comment by coullin** [comment]
额...还是自己没看懂文档， 看你上面的图片才知道 那个jar包应该放在 ja 目录下，我给整到 intellij 的 plugin目录下了。。。

**Comment by tangdu** [comment]
![image](https://github.com/starxg/MyBatisCodeHelperProCrack/assets/1294394/6874ab36-0af8-4be1-832b-f2299b06c47c)
经测试可以成功。

**Comment by tangdu** [comment]
可以关了，操作问题。多看文档
