### ISSUE TITLE
提示破解版，直接关我软件

### ISSUE THREAD

**Issue by hou6663** [starxg/MyBatisCodeHelperProCrack#3]
使用新版1.0.2的，MyBatisCodeHelperPro 3.2.3 ，容易弹出提示窗把我idea都关了，在从数据库生成实体类和dao层代码时，偶然出现这种情况
![QQ截图20230904162512](https://github.com/starxg/MyBatisCodeHelperProCrack/assets/71954648/cf71f4fe-7fa1-41cb-8af9-65fdd547918c)
![QQ截图20230904162814](https://github.com/starxg/MyBatisCodeHelperProCrack/assets/71954648/68782aea-7841-4960-86a8-9bd4e01f9282)

**Comment by starxg** [comment]
能否详细描述一下复现过程？

**Comment by hou6663** [comment]
### 我从数据库点击生成，然后什么参数就选完了之后，提示生成成功，然后下一步代码生成完了，但是弹窗提示是破解版，然后软件就被关了，然后再打开还得再去激活一遍

![QQ截图20230904163919](https://github.com/starxg/MyBatisCodeHelperProCrack/assets/71954648/2c67c1ac-478d-40a9-8bb7-8e0c7ba73d86)

![QQ截图20230904163928](https://github.com/starxg/MyBatisCodeHelperProCrack/assets/71954648/6f76754e-b19f-47b8-a942-65885d84d66f)
3e1411a73f)
![QQ截图20230904163933](https://github.com/starxg/MyBatisCodeHelperProCrack/assets/71954648/9d945c82-bf1a-4bec-92ae-9b8f20b19e4d)
![QQ截图20230904163939](https://github.com/starxg/MyBatisCodeHelperProCrack/assets/71954648/b15f2910-ff99-4fd1-ad17-963b67001f5b)

**Comment by starxg** [comment]
已经复现并尝试[去掉检测](https://github.com/starxg/MyBatisCodeHelperProCrack/blob/1.0.3/src/main/java/com/starxg/janetfilter/plugin/CrackCheckerTransformer.java#L24)类。请尝试使用最新版：https://github.com/starxg/MyBatisCodeHelperProCrack/releases/tag/1.0.3

**Comment by hou6663** [comment]
OK，感谢大佬
