### ISSUE TITLE
你好，请问这个问题的原因是？

### ISSUE THREAD

**Issue by duokebei** [starxg/MyBatisCodeHelperProCrack#5]
![image](https://github.com/starxg/MyBatisCodeHelperProCrack/assets/75022552/c9fcd73e-12b8-4f68-a93c-3914cc19b646)
![image](https://github.com/starxg/MyBatisCodeHelperProCrack/assets/75022552/e7dd5ce4-27ae-47df-8312-610a3b06385c)
![image](https://github.com/starxg/MyBatisCodeHelperProCrack/assets/75022552/9a15a5c9-c136-4c60-a915-de2dcb43b281)

**Comment by starxg** [comment]
下载 https://plugins.jetbrains.com/plugin/9837
